### ISSUE TITLE
renamed sht_git_version files have not uploaded

### ISSUE THREAD

**Issue by nzwiztek** [Sensirion/embedded-sht#34]
Unable to make release due to "no rule to make target 'sht_git_version.c'. It appears the files are missing since the rename.

I will download the older version and rename, however thought you would want to know.

**Comment by abrauchli** [comment]
Hi @nzwiztek many thanks for the report. This only happens when you call make from the driver directory. You first need to build at project level to build this dependency that is common to all SHT drivers.

```bash
cd embedded-sht
make   # needed to generate the file
cd sht3x
make   # must now succeed
```

This is expected to fail. Can you verify, that this is indeed your issue:
```bash
cd embedded-sht
make clean
cd sht3x
make    # must fail due to the missing dependency
```

**Comment by nzwiztek** [comment]
Many thanks @abrauchli this did fix my issue. What confused me is when I went one build back in history the missing files were present in source control.

Again, Thanks

**Comment by abrauchli** [comment]
great, thanks for double-checking @nzwiztek
