### ISSUE TITLE
SHT3x Alert Mode

### ISSUE THREAD

**Issue by will-emmerson** [Sensirion/embedded-sht#53]
I want to be able to set high and low limits for the sensor to wake up an mcu using the alert mode as described here:
https://www.repcomsrl.com/wp-content/uploads/2016/06/SHT3x_Alert_Mode_DIS_V1.pdf

Looking at the code it doesn't seem to mention anything about this though.

**Comment by abrauchli** [comment]
Thank you for your feedback. Indeed, at this point, alerts are not implemented, but we'd be happy to consider and review a pull request, should you decide to implement it.

**Comment by psachs** [comment]
Alert mode implemented on master and will be part of the next release
