### ISSUE TITLE
Dual sensor addresses SHT3x not supported

### ISSUE THREAD

**Issue by qcabrol** [Sensirion/embedded-sht#73]
Hi team,

Just to mention that when going through the sensor integration process, it appears your driver sht3x.h/c is hardcoding the sensor address to the default one and does not allow the use of the alternative one. It also means as in our application we use 2 sensors (one facing indoors, the other facing outdoors) that dynamic addressing to one or the other address is not possible in the current state.

I will submit a PR in that sense, probably as well for the alert support.

**Comment by qcabrol** [comment]
Checking the driver implementation, it was possible to define the alternative address. But not to address in parallel 2 sensors with the 2 addresses. PR submitted.

**Comment by psachs** [comment]
Thank you @qcabrol for extending the driver to support multiple I2C addresses and alert mode
