### ISSUE TITLE
Feature request Raspbery Pi Pico C SDK integration

### ISSUE THREAD

**Issue by anglerfish27** [Sensirion/embedded-sht#79]
I apologize I'm not that savvy in GitHub about how to leave comments, this isn't an "issue" it is a feature request. Would you be kind enough to port an example for the Raspberry Pi Pico using the c SDK only? Meaning no C++ and just pure C. I tried following your instructions to port the I2C SDK objects needed to meet your code but sadly I have failed countless times. I have about 4 of the SHT45 sensors I would really love to use. I don't use Arduino or MicroPython or even Adafruits code (since it's Arduino C++ based). I only program in pure C using the Pico C SDK. 

I would imagine it would take one of your engineers 10 minutes to code this, I'll even pay for a pico if you want just let me know how to fund this and I will! I know it is a big ask from essentially one user but it would go far in the community of Pico fans. I found several others stuck in my situation as well. I sincerely hope you give this some thought and write it out for the pico as an example. The board is blowing up in popularity and there are still many of us who use plain C and Visual Studio Code to interface with it. I would be forever grateful if you could assist the Pico crowd! 

I would bet your engineers would need nothing more than this to code it out:
https://www.raspberrypi.com/documentation/pico-sdk/rp2__common_2hardware__i2c_2include_2hardware_2i2c_8h.html

Hoping you hear the voice of just one customer (who has been loyal to your company with some of your other sensors!) 
Respectfully,

Anglerfish27

**Comment by qfisch** [comment]
Hello @anglerfish27 ,

Sorry for the delay.
I am not sure I understand your issue. Our embedded drivers are written in pure C, they do not use C++ libs.
Did you have a look at the read-me ? Especially this [section](https://github.com/Sensirion/embedded-sht#files-to-adjust-from-embedded-common). That is where you need to configure the I2C configuration for your platform (we do not provide a ready to go HAL for rp-pico, and do not plan to for now)
For the implementation itself, you can get inspired by the [HAL we provide](https://github.com/Sensirion/raspberry-pi-i2c-sht4x/blob/master/sensirion_i2c_hal.c) for full size Raspberry pi. Of course it would need a few adaptations given the pico-sdk but it should help for sure.

I hope it helps,
Cheers.

(We do not hav
